### ISSUE TITLE
Writing polygons with variable number of vertex indices?

### ISSUE THREAD

**Issue by gdevos** [dranjan/python-plyfile#11]
Hi,

First of a big thank you for python-plyfile, it's been working great (mostly ;)

I can't figure out how to write a plyfile with multiple polygons with variable number of indices (20, 13, 4, etc). Or if this is even possible?
Reading those is no problem but how to write?

It breaks for me at:
polygon_array = numpy.array(outf_polygons_tuples,
                                dtype=[('vertex_indices', 'i4', (20,))])
(which I try to load with
pol = PlyElement.describe(polygon_array, 'polygon')
)
I can set the "20" to whatever the length of a polygon is but then it breaks as soon as it gets to a different shape:
ValueError: cannot copy sequence with size 13 to array axis with dimension 20

Can I fill out the polygons vertex indices with null or zero or something so they´re all same length for numpy but different lengths in the PLY file?

Any pointers are much appreciated, including telling me it won't work.

Thanks,
Gerard

**Comment by dranjan** [comment]
@gdevos - The way to do this is have the dtype be `object`:
```python
polygon_list = [[0,1,2],[0,1,2,3],[0,1,2,3,4]]
polygon_array = numpy.empty(len(polygon_list), dtype=[('vertex_indices', 'O')])
# There may be a better way to fill the array, but it's escaping me
for (k, polygon) in enumerate(polygon_list):
    polygon_array[k]['vertex_indices'] = polygon
pol = PlyElement.describe(polygon_array, 'polygon')
```
I'll close the issue now, since this should solve your problem, but please feel free to reopen if you still have issues.
