### ISSUE TITLE
UnicodeDecodeError while reading data

### ISSUE THREAD

**Issue by lilouch** [dranjan/python-plyfile#12]
Hi,

I did not have any problems with Python 2.7.12 but now with Python 3.5 I have a problem and I cannot read anymore my ply file.

My app crash at this following line : 
`plydata = PlyData.read(open(filename))`

And the error message is the following:
```
File "test_read.py", line 5, in <module>
    data = reader.load_data('Model.ply')
  File "/Users/test/visualize_cloud.py", line 69, in load_data
    plydata = PlyData.read(open(filename))
  File "/usr/local/lib/python3.5/site-packages/plyfile-0.4-py3.5.egg/plyfile.py", line 300, in read
  File "/usr/local/lib/python3.5/site-packages/plyfile-0.4-py3.5.egg/plyfile.py", line 246, in _parse_header
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x88 in position 199: invalid start byte
```

Do you have any clues about solving this issue ?

Thank

**Comment by dranjan** [comment]
@lilouch - PLY headers are supposed to be ASCII-encoded.  This is apparently the line of code in plyfile.py where the exception is thrown: https://github.com/dranjan/python-plyfile/blob/master/plyfile.py#L246  Does your PLY header have any non-ASCII bytes?

**Comment by lilouch** [comment]
My bad. Indeed my file was encoded in binary.
However, you may want to make a minor modification concerning the reading in **_parse_header()**. Indeed, depending of which version of Python you use, you can have an error. For example if I'm using python 3.5, I have to remove the decode() part.

```
req_version = (2,5)
cur_versioncur_version = sys.version_info
  if cur_version >= req_version:
                line = stream.readline()
            else :
                line = stream.readline().decode('ascii').strip()
```

Thank

**Comment by dranjan** [comment]
@lilouch - sorry, I'm still confused.  Can you provide a failing test case?  Or just attach a minimal failing example on this issue.

**Comment by lilouch** [comment]
Yes.

So by reading a PLY file (ASCII encoded so it's okey) with Python 3 I have the following error : 
```
Traceback (most recent call last):
  File "test_read.py", line 7, in <module>
    data = reader.load_data("data/Model.ply")
  File "/Users/test.py", line 71, in load_data
    plydata = PlyData.read(open(filename))
  File "/usr/local/lib/python3.5/site-packages/plyfile-0.4-py3.5.egg/plyfile.py", line 305, in read
  File "/usr/local/lib/python3.5/site-packages/plyfile-0.4-py3.5.egg/plyfile.py", line 251, in _parse_header
AttributeError: 'str' object has no attribute 'decode'
```

Whereas using python 2, I'm able to read correctly the file.
By investigating, I noticed that the error was because of the following lines in `_parse_header()`
```
 line = stream.readline().decode('ascii').strip()
            keyword = _split_line(line, 1)[0]

            if keyword == 'end_header':
                break

            elif keyword in comments.keys():
                lines.append([keyword, line[len(keyword)+1:]])
            else:
                lines.append(line.split())
```

It turns out that by using Python 3 you don't need anymore the `decode()` part.
So I have modified the code to make it work by just removing `decode().strip()`

```
      if cur_version >= req_version:
                line = stream.readline()
            else :
                line = stream.readline().decode('ascii').strip()
```

**Comment by dranjan** [comment]
@lilouch - what I meant: **please provide a minimal example of a PLY file that demonstrates this issue.** You can attach it to the issue.  I need to be able to reproduce the issue and test that the proposed solution works before changing the code.

Also, just to be clear:
- All valid PLY files are supported, ASCII and binary (big-endian and little-endian). However, the PLY *header* needs to be ASCII-encoded.
- The code has been tested rigorously on Python 2 and Python 3, and I was under the impression that it worked on both.  Although it isn't explicitly listed in the testing configuration, I have also tested on Python 3.5 (in addition to Python 3.4).

**Comment by lilouch** [comment]
Okey please find attached the concerned file.

I'm sure you already test a lot of things and I did not say the opposite.
It's maybe my header is not well encoded.

So, even if the data points are binary encode, as soon as the header is ASCII-encoded, it should work ?

[Model.ply.zip](https://github.com/dranjan/python-plyfile/files/802984/Model.ply.zip)

**Comment by dranjan** [comment]
Okay, I think I see what happened: you need to open the file in binary mode.  Either of the following should work:

    plydata = PlyData.read(filename)

or

    plydata = PlyData.read(open(filename, 'rb'))

I'm not sure why Python 2 allows it without 'rb' and Python 3 doesn't, but you should always use 'rb' as the mode when reading PLY files.  I have updated the example in the documentation to reflect this.

**Comment by lilouch** [comment]
Okey great. Thank you !
