### ISSUE TITLE
extra '\r' character in the header

### ISSUE THREAD

**Issue by Kai-46** [dranjan/python-plyfile#18]
See the attached screenshot of the ply file created by this package opened in Vim.
![vim](https://user-images.githubusercontent.com/21653654/46927792-4bcdea00-d005-11e8-9975-2357625a7202.png)

**Comment by dranjan** [comment]
If you're writing to a file object (not a filename), can you make sure you're opening it in binary mode (mode='wb')?

**Comment by dranjan** [comment]
Closing because I don't think this is a `plyfile` bug.
