### ISSUE TITLE
How do you check if PLY contains a property

### ISSUE THREAD

**Issue by meder411** [dranjan/python-plyfile#22]
I have some PLY files that contain variable properties, some have XYZ only, some have XYZ+normals, some have XYZ+RGB, etc. I want to write a loader function that will parse any of these. How can I test if properties exist? For example, if `nx`, `ny`, `nz` are there.

**Comment by dranjan** [comment]
I can think of a couple ways to do this.  The simplest is probably something like:
```python
>>> ply = PlyData.read('examples/tet.ply')
>>> props = [p.name for p in ply['vertex'].properties]
>>> props
['x', 'y', 'z']
>>> 'nx' in props
False
```
Another way would be to assume the property is there by using (for example) `ply['vertex']['nx']` in your code, which will raise an exception if the property doesn't exist, which of course you can catch and act on.

I guess it would be nice to be able to do something like `'nx' in ply['vertex']`, but `PlyElement` doesn't currently support that.

**Comment by jiapei-nexera** [comment]
BTW, what are the meaning of nx, ny, nz ??
how many x/y/z coordinates?

**Comment by dranjan** [comment]
Sorry - found this in my emails. `(nx, ny, nz)` is a vertex's normal vector in this context.
