### ISSUE TITLE
Instance copy overwrites instance values

### ISSUE THREAD

**Issue by erezposner** [dranjan/python-plyfile#23]
Hello I am trying to perform a simple task.

I would like to read a ply file. 
copy it to another plydata instance, then change the vertices values in the copy while keeping the original instance values the same.

See this code below

 ```
print(original_plydata['vertex']['x'][0])

copy_plydata = PlyData([plydata['vertex']],
                      text=False, byte_order='<')
copy_plydata['vertex']['x'][0] = -100
print(copy_plydata['vertex']['x'][0])
print(original_plydata['vertex']['x'][0])
```
I would expect the first print to plot the read value of the original (lets say 5).
The second print must plot -100, and the third print 5 again.

But for some reason the third print plots -100.
What could cause this issue? 
thank you

**Comment by dranjan** [comment]
Yeah, this is expected behavior.  In your example, `original_plydata` and `copy_plydata` are sharing a single `PlyElement` instance, so you can't change one without also changing the other.

To create a true copy, you need to create a new `PlyElement` and also copy the underlying NumPy array:
```python
from plyfile import PlyData, PlyElement

original_plydata = PlyData.read('examples/tet.ply')

print(original_plydata['vertex']['x'][0])

copy_plydata = PlyData(
    [PlyElement.describe(original_plydata['vertex'].data.copy(), 'vertex')],
    text=False, byte_order='<'
)
copy_plydata['vertex']['x'][0] = -100
print(copy_plydata['vertex']['x'][0])
print(original_plydata['vertex']['x'][0])
```

**Comment by erezposner** [comment]
Thank you
