### ISSUE TITLE
Writing a ply file after modifications to the input file 

### ISSUE THREAD

**Issue by nys09** [dranjan/python-plyfile#25]
[Trialcode.txt](https://github.com/dranjan/python-plyfile/files/3438693/Trialcode.txt)

I am new to programming and I am having issue with writing a new .ply file after modifying vertex normals and the r, g, b values of each vertex. Following is the modification I am doing for normals.
plydata.elements[0].data['nx']=np.asarray(normals[:,0])
plydata.elements[0].data['ny']=np.asarray(normals[:,1])
plydata.elements[0].data['nz']=np.asarray(normals[:,2])

Now, as I already have the modified structured arrays, I am using PlyElement.describe to create the PlyElement instances:
el = PlyElement.describe(plydata['vertex'].data,'vertex')
el2 = PlyElement.describe(plydata['face'].data,'face')

Now, I have two instances (one for vertices and one for faces). Can you please tell me how to use them to write a final .ply file merging both vertices and faces? All I have so far is 

PlyData([el], text=True).write('some_ascii1.ply')
PlyData([el2], text=True).write('some_ascii1.ply') 

The second command overrides the first one and data regarding only faces is on my output file. How can I merge both into my output file? Attached txt file is the code I have so far.
--
Thanks

**Comment by dranjan** [comment]
You should put both elements in a single `PlyData` instance:
```python
PlyData([el, el2], text=True).write('some_ascii1.ply')
```

**Comment by nys09** [comment]
That worked. Thank you very much.
