### ISSUE TITLE
Why do I get, ValueError: two properties with same name when I try to access .ply files using plyfile API ?

### ISSUE THREAD

**Issue by arunumd** [dranjan/python-plyfile#28]
I am working with a project that requires accessing point cloud data in the form of .ply files and converting them into numpy arrays for running a deep learning algorithm. When I try to access my .ply files from my directory, I get the error "_**ValueError: two properties with same name**_"

The following is my code -

```
import glob
import numpy as np
from plyfile import PlyData, PlyElement
arr = np.array([])

for filepath in glob.iglob('/content/drive/My Drive/PLY Files/*.ply'):
  plyFile = PlyData.read(filepath)
  plyFile.elements[0].properties
```

The following is the error -
```
/usr/local/lib/python3.6/dist-packages/plyfile.py in _index(self)
    549                                      for prop in self._properties)
    550         if len(self._property_lookup) != len(self._properties):
--> 551             raise ValueError("two properties with same name")
    552 
    553     def ply_property(self, name):

ValueError: two properties with same name
```

**Comment by dranjan** [comment]
Sorry, I had glossed over your issue.  Would you mind sharing the PLY header?

**Comment by dranjan** [comment]
Answered [here](https://stackoverflow.com/a/59528197/8333322).
