### ISSUE TITLE
Distribute package as wheel

### ISSUE THREAD

**Issue by glostis** [dranjan/python-plyfile#30]
Hi,

Thanks for the great work on this package, it is very handy!

I'd like to know if you would agree to distribute this package as a [wheel](https://pythonwheels.com/), along with the `sdist` you currently distribute?

I can open up a PR to automate the release process with Travis CI if it is of interest to you. It is fairly easy ([docs](https://docs.travis-ci.com/user/deployment/pypi/)), I have already added it on a few packages.

**Comment by dranjan** [comment]
Yes, I think I can start uploading wheels.  I just looked into it, and it seems pretty straightforward.

Thanks for the pointer on release automation.  I've been uploading releases manually (using `twine`), which has been fine so far, but I'll consider that if it starts getting burdensome.

**Comment by dranjan** [comment]
All right, the latest version has a wheel: https://pypi.org/project/plyfile/0.7.2/#files  I tested the download and everything seems to be working.  Wheels will be uploaded from now on.

**Comment by glostis** [comment]
:+1:  thanks a lot!
