### ISSUE TITLE
Convert plydata to structured numpy array

### ISSUE THREAD

**Issue by luczeng** [dranjan/python-plyfile#31]
Hello,

I would like to convert a load ply file vertices to a structure numpy array to be further processed by another library (pdal).

My problem is that pdal only accepts structured array with fields 'x','y','z' fields, of the same form that plyfile uses to write to disk. The input is a mesh ply file.

I have tried the following:

```
plydata = PlyData.read(path2plyfile)
vertices = plydata["vertex"].data
```

However the result is a memmap, not a structured array as I would like:

`print(type(vertices))`

gives:

`<class 'numpy.memmap'>
`

What could I do?

**Comment by dranjan** [comment]
If the other library specifically requires a `numpy.ndarray`, then you can convert it using `numpy.array` or `numpy.asarray`:
```python
vertices = numpy.array(plydata["vertex"].data)
```

**Comment by luczeng** [comment]
Ok, great, it worked
