### ISSUE TITLE
element 'vertex': row 0: property 'x': malformed input

### ISSUE THREAD

**Issue by protactinium91** [dranjan/python-plyfile#32]
When trying to run  write-h5py I am getting this error

> element 'vertex': row 0: property 'x': malformed input

The ply file has been genereted by the make_ply script
The file looks like this: 

> ply
> format ascii 1.0
> comment VCGLIB generated
> element vertex 400
> property float x
> property float y
> property float z
> element face 0
> property list uchar int vertex_indices
> end_header
> ﻿-0.178355 7.263247 7.505326
> 28.151129 15.29806 9.369929
> 

and so on

What could be the reason?

**Comment by dranjan** [comment]
When I copy-paste your example into a text editor (vim), I see a unicode character 0xfeff (byte-order mark) at the beginning of the vertex data, so I suspect that's there in your PLY file also.  The parser is probably choking on that.

**Comment by protactinium91** [comment]
Exactly, I have solved this yesterday after many hours. At first I thought the make-ply makes this, but finally I have found that my base program that creates the pointcloud adds the BOM
