### ISSUE TITLE
editing comments 

### ISSUE THREAD

**Issue by cell-a** [dranjan/python-plyfile#33]
how to edit comment / comments by code 
add comment , edit , find & replace in comment

**Comment by dranjan** [comment]
The `comments` attribute of a `PlyData` or `PlyElement` instance can be assigned to directly.  Note that you can do it like this:
```python
ply_data = PlyData.read(...)
comments = ply_data.comments
comments[0] = ...
ply_data.comments = comments
```
but not like this:
```python
ply_data = PlyData.read(...)
ply_data.comments[0] = ...
```
because the `comments` attribute is actually a property that returns a new list, which might not be obvious.

If that doesn't work for you, you'll need to be more specific.

**Comment by cell-a** [comment]
although the ply file has comments but it return empty list ! 
i'd used this code 

`ply_data = PlyData.read(filePath)`
`comments = ply_data.comments`
`print(comments)`
`>>>> []`
put while tracking plyfile.py 
i founded all comments in elements ! 
and the header also contain the comments 
.. 
now i need to delete all comments and add new list , or find & replace in comment 
or find & replace in header 
i'm tried to use 
`ply_data.write()` 
but it didn't work

**Comment by dranjan** [comment]
Yes, comments that come after an `element` line in the header are owned by the corresponding `PlyElement` instance.  When the file is written out, all the comments for that element are put immediately after the `element` line, irrespective of where they may have been in the original file.

You're going to have to be more specific than "it didn't work."

**Comment by cell-a** [comment]
simply i need to edit the header in existing ply file , 
& the points in binary 
i made this function . 

`def write_header(self, stream,oldt='',newt=''):
        self.text=True
        stream=open(stream, 'r+')
        my_header=pp.header
        new_header=my_header.replace(oldt,newt)
        try:
            stream.write(my_header.replace(my_header,new_header))
        finally:
            print("Edited")
            stream.close()`

`ply_data=PlyData.read(fileToSearch)`
 `ply_data.write_header(fileToSearch,textToSearch,textToReplace)`

it's working partly 
the new header already inserted in the file but i'ts appended before the old header! 
the ply file

**Comment by dranjan** [comment]
I think you want something like this:
```python
def edit_comments(comments):
    # code here to modify comments
    return comments


ply_data = PlyData.read(fileToSearch)
ply_data.comments = edit_comments(ply_data.comments)
for element in ply_data.elements:
    element.comments = edit_comments(element.comments)
ply_data.write(fileToSearch)
```

**Comment by cell-a** [comment]
thank you for following & support 
i think it will work   

i wrote the following code but i have 2 errors 

`import plyfile`
`from plyfile import PlyData,PlyElement`
`def edit_comments(comments):`
   `   # code here to modify comments`
  `  i=0`
   ` for c in comments:`
    `    if c.startswith('c:'):`
     `       comments[i]=c.replace(textToSearch ,textToReplace)`
      `  i=i+1`
    `return comments`

`print ("Text to search for:")`
`textToSearch = input( "> " )`

`print ("Text to replace it with:")`
`textToReplace = input( "> " )`

`print ("File to perform Search-Replace on:")`
`fileToSearch  = input( "> " )`

`ply_data = PlyData.read(fileToSearch)`
`ply_data.comments = edit_comments(ply_data.comments)`
`for element in ply_data.elements:`
 `   element.comments = edit_comments(element.comments)`
`ply_data.write(fileToSearch)`

`input( '\n\n Press Enter to exit...' )`

i have many ply files 
some ply files give error in reading :  
(please note that the file is large (1.5 GB) also i have bigger files from 1 GB to 10 GB 
the following is error while : 
`ply_data = PlyData.read(fileToSearch)`


> self._data = _np.empty(self.count, dtype=self.dtype(byte_order))
> MemoryError: Unable to allocate array with shape (50546988,) and data type [('x', '<f4'), ('y', '<f4'), 
> ('z', '<f4'), ('nx', 
> '<f4'), ('ny', '<f4'), ('nz', '<f4'), ('diffuse_red', 'u1'), ('diffuse_green', 'u1'), ('diffuse_blue', 'u1'), 
> ('diffuse_alpha', 'u1')]

and the 2nd Error 
while i'm using small file (200MB) 
its working till final step :
`ply_data.write(fileToSearch)`

> File "C:\Users\Ahmed\AppData\Local\Programs\Python\Python37-32\lib\site-packages\plyfile.py",  > line 469, in _open_stream    
>   return (True, open(stream, read_or_write[0] + 'b'))
> OSError: [Errno 22] Invalid argument: 'D:\\python 3012\\scaled.ply'

is there another way to edit header or comments without writing the all file ? 
because the large files will take long time in writing

**Comment by dranjan** [comment]
For the first error: it appears that `plyfile` wasn't able to memory-map the element, so it's falling back to explicit allocation and copying.  I'm not sure why it couldn't memory-map the file, but in general memory-mapping is not guaranteed.  So assuming it's not a `plyfile` bug and the file really cannot be memory-mapped, I think your best option is to roll something together yourself not using the `plyfile` official API.  The efficient way to do this would probably involve
1. carefully parsing just the header from the file,
2. modifying the header,
3. writing it to a new file, and
4. blindly copying the rest of the file data to the new file without any kind of parsing.

There are some internal APIs inside `plyfile` that may simplify some of this.  Specifically, there's `PlyData._parse_header` that parses just the header and creates an "incomplete" `PlyData` instance without reading the data itself, and it also positions the file stream correctly so you know where the data begins.  And, as you are already aware, there's the `header` attribute of `PlyData` instances that should still work.  Those two things should take care of steps 1 and 3.  I think you've already figured out 2 (the same function should work), and 4 should be straightforward.

I need to emphasize, though, that `PlyData._parse_header` is (at least for now) a private function, so this method is not guaranteed to work in future versions of `plyfile`.  To be safe, you may need to introduce a hard dependency on this specific `plyfile` version into your code, or copy `plyfile.py` into your project.

For the second error: sorry, I'm not sure what's happening there.  It appears that it couldn't open the file for writing.

**Comment by cell-a** [comment]
i agree with you in the 4 points 
that's what i need really 
but there are problems too :( 
while trying to use `ply_data._parse_header` this error occurred 
`while parser.consume(stream.readline()):`
`AttributeError: 'str' object has no attribute 'readline'`

i'm tried to write only the header 
with different ways 
but always i effect the data ! 
or it's error in encoding 
also i'm tried to use it as binary 
but its effecting in the str ! 
could you help please "with code" in how to edit the header only and copy the data blindly ?
or edit in the file and stop when reach `'end_header'` line

**Comment by dranjan** [comment]
> i agree with you in the 4 points
> that's what i need really
> but there are problems too :(
> while trying to use `ply_data._parse_header` this error occurred
> `while parser.consume(stream.readline()):`
> `AttributeError: 'str' object has no attribute 'readline'`

Right, of course you need to open the file first (in binary mode).  At this point you're going to need to be able to read the code and understand what it's doing, since you're using functionality that's supposed to be internal to the package.

> i'm tried to write only the header
> with different ways
> but always i effect the data !
> or it's error in encoding
> also i'm tried to use it as binary
> but its effecting in the str !
> could you help please "with code" in how to edit the header only and copy the data blindly ?
> or edit in the file and stop when reach `'end_header'` line

I agree that simply editing inside the header would be extremely convenient, and that could be done using memory mapping.  Unfortunately, as far as I know, that doesn't allow you to change the length of the header, so I don't think that's a viable solution.  But if you know the header's length won't change, you can simply memory-map the whole file and edit the header in place.

To copy the PLY data in Python, the easiest way to do it is probably with the [`read`](https://docs.python.org/3.7/library/io.html#io.BufferedIOBase.read) and [`write`](https://docs.python.org/3.7/library/io.html#io.BufferedIOBase.write) methods of the file objects, which should also be reasonably efficient if you do it in chunks.  Around 1024 to 4096 bytes is probably what I'd try first.

Another idea is to copy the data using an external tool, not in the Python code, using the `tell` method of the PLY file after parsing the header to determine where the data begins and using the external tool to copy the file data starting at that offset.

I'm sorry, but at this point it's clear that the problems you need to solve aren't directly related to the `plyfile` package, so I'm going to have to close this issue.

**Comment by cell-a** [comment]
yes you are tight , 
i'd wrote new code totally without using ply file and the problem solved 
i wrote code to copy ply file in binary mode and the header decoded and edited then appended in new file 
Many Thanks for your support
