### ISSUE TITLE
Binary PLY stays memory mapped after read on Windows

### ISSUE THREAD

**Issue by ALfuhrmann** [dranjan/python-plyfile#37]
[monkey.zip](https://github.com/dranjan/python-plyfile/files/5365107/monkey.zip)

I found myself unable to delete a .PLY file after reading from it.
Further tests showed that binary PLYs stay memory mapped after reading.

To reproduce:

```
import os
from plyfile import PlyData

filename = 'monkey_bin.ply'
plydata = PlyData.read(filename)
os.remove(filename)`
```

Produces on Windows:
`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'monkey_bin.ply'`

This does not happen if I remove memory mapping from PlyElement._read():

```
        #elif _can_mmap(stream) and not self._have_list:
        elif False and not self._have_list:
```

**Comment by dranjan** [comment]
I wasn't able to reproduce, so it may be Windows-specific. But in any case, it's easy enough to make memory-mapping optional as a workaround, which I've done on `master`. Might you be able to check if that works around the issue? You would need to opt out of memory mapping by using
```python
plydata = PlyData.read(filename, mmap=False)
```

**Comment by ALfuhrmann** [comment]
This works fine, thank you!

In the [numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.memmap.html) they say:
`Delete the memmap instance to close the memmap file.`
and
`Deletion flushes memory changes to disk before removing the object:`

so maybe it would work with mmapping when you explicitly 
`del _np`
after using it? Maybe just before closing the file/returning from read? 
I could not find the correct place to do this in the code.

**Comment by dranjan** [comment]
You can `del plydata` and that should let you delete the file, but then you won't have the PLY data in your program any more either, which seemed undesirable.

`del _np` would not do anything useful.

**Comment by dranjan** [comment]
Sorry, forgot to add: thanks for verifying the workaround, @ALfuhrmann!

**Comment by ALfuhrmann** [comment]
Just to leave this here for others with the same problem:
It would have also worked for me if I deleted the PLY data structure after use and before removing the file:

```
import os
from plyfile import PlyData

filename = 'monkey_bin.ply'
plydata = PlyData.read(filename)
# do something with plydata
# ...

# delete data & file
del plydata   # <----- this delete frees the memory mapped file on Windows
os.remove(filename)
```

But if you need the data after deleting the input file, the above #38 tweak is necessary.
