### ISSUE TITLE
Writing colored vertices

### ISSUE THREAD

**Issue by bk1285** [dranjan/python-plyfile#4]
Hi dranjan,

thanks for providing this library!

I would like to use it, but I'm currently experiencing a little issue when writing out colored pointclouds:
I have two numpy-arrays:

  * one holding 3d coordinates

        vertex = numpy.array([(0, 0, 0),
                              (0, 1, 1),
                              (1, 0, 1),
                              (1, 1, 0)],
                             dtype=[('x', 'f4'), ('y', 'f4'), ('z', 'f4')])

  * one holding color information

        vertex_color = numpy.array([(0, 255, 0),
                                    (0, 255, 255),
                                    (255, 0, 255),
                                    (255, 255, 0)],
                                   dtype=[('red', 'u1'), ('green', 'u1'), ('blue', 'u1')])

Is there any way to pass both of these directly to your library for writeout?
What would you propose to achieve the following output:

    ply
    format ascii 1.0
    element vertex 4
    property float x
    property float y
    property float z
    property uchar red
    property uchar green
    property uchar blue
    end_header
    0.0 0.0 0.0 0 255 0
    ...

I would be thankful for your feedback.

Regards,
Bernd

**Comment by dranjan** [comment]
@bk1285 - Currently, there's no way to directly supply more than one array for a single element, so you have to create a single numpy array with all the fields.   Here's one possibility:

```python
n = len(vertex)
assert len(vertex_color) == n

vertex_all = numpy.empty(n, vertex.dtype.descr + vertex_color.dtype.descr)

for prop in vertex.dtype.names:
    vertex_all[prop] = vertex[prop]

for prop in vertex_color.dtype.names:
    vertex_all[prop] = vertex_color[prop]

ply = PlyData([PlyElement.describe(vertex_all, 'vertex')], text=True)
ply.write(sys.stdout)
```

I'm going to close this issue because I think the above should solve your problem, but please reopen if you still have issues.

**Comment by bk1285** [comment]
@dranjan - Thanks a lot! Works perfect by now... :)

**Comment by legel** [comment]
FYI for future readers (since this helped me), I found that the very last line required what seems to be an update to the API:

Instead of:
```python
ply = PlyData([PlyElement.describe(vertex_all, 'vertex')], text=True)
ply.write(sys.stdout)
```

Just do:
```python
PlyData([PlyElement.describe(vertex_all, 'vertex')], text=True).write(sys.stdout)
```

Otherwise this error comes up:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.local/lib/python3.6/site-packages/plyfile.py", line 408, in write
    stream.write(self.header.encode('ascii'))
TypeError: write() argument must be str, not bytes
```

For the author, I would suggest putting a nice simple example like this with on the home page documentation.

**Comment by legel** [comment]
Canonical point cloud save example (which you're welcome to publish on the homepage if you wish):

```python
import numpy as np
from plyfile import PlyData, PlyElement

# define 3D point cloud data
n = 10000
x = np.random.uniform(low=-100.0, high=100.0, size=(n,))
y = np.random.uniform(low=-100.0, high=100.0, size=(n,))
z = np.random.uniform(low=-100.0, high=100.0, size=(n,))
red = np.random.randint(low=0, high=255, size=(n,))
green = np.random.randint(low=0, high=255, size=(n,))
blue = np.random.randint(low=0, high=255, size=(n,))

# connect the proper data structures
vertices = np.empty(n, dtype=[('x', 'f4'), ('y', 'f4'), ('z', 'f4'), ('red', 'u1'), ('green', 'u1'), ('blue', 'u1')])
vertices['x'] = x.astype('f4')
vertices['y'] = y.astype('f4')
vertices['z'] = z.astype('f4')
vertices['red'] = red.astype('u1')
vertices['green'] = green.astype('u1')
vertices['blue'] = blue.astype('u1')

# save as ply
ply = PlyData([PlyElement.describe(vertices, 'vertex')], text=False)
ply.write("binary_point_cloud.ply")
```
![save_point_cloud_to_ply_from_python](https://user-images.githubusercontent.com/1915466/91644335-5ea40900-ea3b-11ea-8f4a-04d0b5073c08.png)

**Comment by dranjan** [comment]
> I found that the last line did not work:
> 
> ```python
> ply = PlyData([PlyElement.describe(vertex_all, 'vertex')], text=True)
> ply.write(sys.stdout)
> ```
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/user/.local/lib/python3.6/site-packages/plyfile.py", line 408, in write
>     stream.write(self.header.encode('ascii'))
> TypeError: write() argument must be str, not bytes
> ```
> 

My bad. I believe it doesn't work because `sys.stdout` is a text-mode output stream. 

> What did work for me was to specify a filename in write( ):
> 
> ```python
> PlyData([PlyElement.describe(vertex_all, 'vertex')], text=True).write("hello.ply")
> ```
> 

Right, or a binary-mode file-like object should work as well. For `sys.stdout`, it would need to be `ply.write(sys.stdout.buffer)` instead. Source: https://bugs.python.org/issue4571 (old discussion, but seems still valid)

> For the author, I would suggest putting a nice simple example like this on the home page documentation.

Yeah, the README could probably use an update.
