### ISSUE TITLE
Read Binary Ply file and write the convert binary data to ascii in output.ply file

### ISSUE THREAD

**Issue by nikhilpatil99** [dranjan/python-plyfile#41]
How to convert the binary ply file to ASCII ply file  and how to give binary ply file path in the code and outfile

**Comment by nikhilpatil99** [comment]
How to convert the binary ply file to ASCII ply file  and how to give binary ply file path in the code and outfile

**Comment by dranjan** [comment]
You can use this pattern:
```Python Console
>>> from plyfile import PlyData
>>> data = PlyData.read('somefile.ply')
>>> data.text = True
>>> data.comments = data.comments + ['original path: somefile.ply']
>>> data.write('newfile.ply')
```
(Note that `data.comments.append(...)` won't work: you need to assign the field directly as above.)

**Comment by nikhilpatil99** [comment]
> You can use this pattern:
> 
> ```python
> >>> from plyfile import PlyData
> >>> data = PlyData.read('somefile.ply')
> >>> data.text = True
> >>> data.comments = data.comments + ['original path: somefile.ply']
> >>> data.write('newfile.ply')
> ```
> 
> (Note that `data.comments.append(...)` won't work: you need to assign the field directly as above.)


This is not working.....file is converted in ASCII but not all values
I have uploaded the files please check it....it does not support
ort .ply extension so I converted it to txt...
1.BInary.txt:- Original Binary file which I want to convert to ASCII using python 
2.ASCII.txt:- I have converted the binary file to ASCII using meshlab . Actual output how I want from python code...
3.newfile.txt:-  The Binary conversion to the ASCII file is not correct. which I got from your suggested python code above.
while checking files please convert again all files above  .txt to .ply  extension so you can get it...
Thanks in advance


[newfile.txt](https://github.com/dranjan/python-plyfile/files/6047330/newfile.txt)
[ASCII.txt](https://github.com/dranjan/python-plyfile/files/6047370/ASCII.txt)
[Binary.txt](https://github.com/dranjan/python-plyfile/files/6047371/Binary.txt)

**Comment by dranjan** [comment]
Sorry, I'm confused. Your `Binary.txt` doesn't appear to be a valid PLY file. The header declares the `vertex` element with 442337 elements, with 27 bytes per vertex, which would be about 11.9 megabytes, but your file is clearly much smaller. Thus, for me,`plyfile` is not able to load it and throws an exception:
```Python Console
>>> from plyfile import PlyData
>>> ply = PlyData.read('Binary.txt')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dranjan/src/python-plyfile/plyfile.py", line 397, in read
    elt._read(stream, data.text, data.byte_order, mmap)
  File "/home/dranjan/src/python-plyfile/plyfile.py", line 652, in _read
    max_bytes // dtype.itemsize)
plyfile.PlyElementParseError: element 'vertex': row 584: early end-of-file
```
This is the correct and expected behavior.

If you're getting different results, please provide a complete and minimal example script so that I can try to reproduce it.

**Comment by nikhilpatil99** [comment]
please Can i get your email id or can you mail me so I can share my ply files and binary file ...on github it is unable to share a ply greater than 10 mb ...so you can get clear idea....
my mail id:- patilnikhil9090@gmail.com
Thanks in advance

**Comment by dranjan** [comment]
Sorry, getting back to this now.

Regarding email, I'd prefer to keep the discussion public if at all possible.

- I believe the attachment size limit for non-image files on GitHub is 25MB ([source](https://docs.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests)).
- Can you try putting your files in a ZIP archive? That may additionally reduce the size.
- Alternatively, can you make a smaller file that demonstrates the issue you're having?

**Comment by dranjan** [comment]
I'm going to assume this issue was solved and not a `plyfile` bug. Please reopen the issue if that's incorrect.

**Comment by Zvyozdo4ka** [comment]
> You can use this pattern:
> 
> ```python
> >>> from plyfile import PlyData
> >>> data = PlyData.read('somefile.ply')
> >>> data.text = True
> >>> data.comments = data.comments + ['original path: somefile.ply']
> >>> data.write('newfile.ply')
> ```
> 
> (Note that `data.comments.append(...)` won't work: you need to assign the field directly as above.)

i wrote exactly, as you recommended, but it always throws an error:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 1: ordinal not in range(128)`

Could you recommend the way to resolve it? My ply file comprises edges too

```ply
format binary_little_endian 1.0
comment Created by Open3D
element vertex 300202
property double x
property double y
property double z
element edge 290788
property int vertex1
property int vertex2
end_header```

**Comment by dranjan** [comment]
@Zvyozdo4ka I'm guessing it's something simple, but I'm not immediately seeing it.
- Can you post the full traceback?
- If you're able to attach an example file, I can try to reproduce it.

**Comment by Zvyozdo4ka** [comment]
@dranjan Hello. Thank you for your quick response. 

1. The file, i am working with is [here](https://drive.google.com/file/d/1vANb2m9rOwPAeGCaJrXQVHqF4iLUVfmN/view?usp=sharing). 

2. Here is the [link](https://colab.research.google.com/drive/1MVaq-Rx8bv1TtXe97XyV_KcW-lSACSdd?usp=sharing) to these lines of code in colab or you can view full traceback here:
```
UnicodeDecodeError                        Traceback (most recent call last)
[<ipython-input-64-fab98d365b29>](https://localhost:8080/#) in <cell line: 3>()
      1 from plyfile import PlyData
      2 
----> 3 data = PlyData.read('/content/man_perm.ply')
      4 data.text = True
      5 data.comments = data.comments + ['original path: man_perm.ply']

3 frames
[/usr/local/lib/python3.10/dist-packages/plyfile.py](https://localhost:8080/#) in read(stream, mmap, known_list_len)
    158         (must_close, stream) = _open_stream(stream, 'read')
    159         try:
--> 160             data = PlyData._parse_header(stream)
    161             if isinstance(stream.read(0), str):
    162                 if data.text:

[/usr/local/lib/python3.10/dist-packages/plyfile.py](https://localhost:8080/#) in _parse_header(stream)
    119     @staticmethod
    120     def _parse_header(stream):
--> 121         parser = _PlyHeaderParser(_PlyHeaderLines(stream))
    122         return PlyData(
    123             [PlyElement(*e) for e in parser.elements],

[/usr/local/lib/python3.10/dist-packages/plyfile.py](https://localhost:8080/#) in __init__(self, stream)
   1265         PlyHeaderParseError
   1266         """
-> 1267         s = self._decode(stream.read(4))
   1268         self.chars = []
   1269         if s[:3] != 'ply':

[/usr/local/lib/python3.10/dist-packages/plyfile.py](https://localhost:8080/#) in _decode(s)
   1292         if isinstance(s, str):
   1293             return s
-> 1294         return s.decode('ascii')
   1295 
   1296     def __iter__(self):

UnicodeDecodeError: 'ascii' codec can't decode byte 0xb2 in position 1: ordinal not in range(128)
```

Thank You!

**Comment by dranjan** [comment]
I downloaded the file and tried this in `ipython`, and...it worked!
```
In [3]: data = PlyData.read('/home/dranjan/Downloads/man_perm.ply')

In [4]: data
Out[4]: PlyData((PlyElement('vertex', (PlyProperty('x', 'double'), PlyProperty('y', 'double'), PlyProperty('z', 'double')), count=300202, comments=[]), PlyElement('edge', (PlyProperty('vertex1', 'int'), PlyProperty('vertex2', 'int')), count=290788, comments=[])), text=False, byte_order='<', comments=['Created by Open3D'], obj_info=[])

```
I also looked at the file in a hex editor and didn't find that byte `0xb2` anywhere in the header, so it appears that something is different between the file you shared and the file the notebook is trying to read.

To continue debugging this, I suggest opening the file as a binary stream in Python and dumping the first 100 bytes or so as a buffer. This is what I get:
```
In [6]: with open('/home/dranjan/Downloads/man_perm.ply', 'rb') as f:
   ...:     b = f.read(100)
   ...: 

In [7]: b
Out[7]: b'ply\nformat binary_little_endian 1.0\ncomment Created by Open3D\nelement vertex 300202\nproperty double '
```
If you're able to run Python locally, you can also try what I did by downloading the file and opening it with `PlyData.read`.

**Comment by Zvyozdo4ka** [comment]
@dranjan Thank you so much for your help and time! It worked
