### ISSUE TITLE
floating point image of openCV to ply file

### ISSUE THREAD

**Issue by minewarriorsSchool** [dranjan/python-plyfile#43]
Hi all! With openCV I generate a pointcloud with the reprojectImageto3D method.

this returns a 3dImage array that looks like (row, colum, (x,y,z)).

Currentely I try to generate a ply file from this image like this:
```
def writePly(_3dImage):
    face_data = _3dImage
    ply_faces = numpy.empty(len(_3dImage), dtype=[('vertex_indices', 'i4', (3,))])
    ply_faces['vertex_indices'] = face_data
    el = PlyElement.describe(ply_faces, 'face')
    PlyData([el]).write('pointcloudStuff/pointcloud_binary.ply')
    PlyData([el], text=True).write('pointcloudStuff/pointcloud_ascii.ply')
    PlyData([el], byte_order='>').write('pointcloudStuff/pointcloud_endian_binary.ply')
```
But generates the following error:

Traceback (most recent call last):
  File "D:/parcel-detection-AWL/testOpencv/yolact_Network/mainPointCloudTest.py", line 81, in <module>
    main()
  File "D:/parcel-detection-AWL/testOpencv/yolact_Network/mainPointCloudTest.py", line 42, in main
    writePly(pc)
  File "D:/parcel-detection-AWL/testOpencv/yolact_Network/mainPointCloudTest.py", line 62, in writePly
    ply_faces['vertex_indices'] = face_data
ValueError: could not broadcast input array from shape (1536,2048,3) into shape (1536,3)

I tried a few other things but then I receive the "only one dimensional arrays are supported" error.

Would love to hear your solution for this. It is probably pretty easy, but I can not see it right now.

**Comment by dranjan** [comment]
I see a couple of issues here:
1. If it's literally a point cloud, that's probably not represented well by a `face` element. `face` is usually supposed to be a list of mesh polygons, each being represented by its vertices, each vertex being represented as an index into the `vertex` array, which is a separate PLY element. The vertices of the point cloud would normally just go into that `vertex` element.
2. It looks like your input is a 3D array, which would make sense if you have three coordinates per (row, column) pair in your image. Before encoding as a PLY file, though, you would need to flatten the two (row, column) dimensions into one, with something like
    ```python
    (rows, columns) = _3dImage.shape[:2]
    flattened_image = _3dImage.reshape(rows*columns, -1)
    ...
    ```
   You should then be able to call `PlyElement.describe` on the flattened array. Unfortunately, the width and height of the image won't be directly captured in the PLY file unless you put it in a header comment or something like that.

**Comment by minewarriorsSchool** [comment]
> I see a couple of issues here:
> 
> 1. If it's literally a point cloud, that's probably not represented well by a `face` element. `face` is usually supposed to be a list of mesh polygons, each being represented by its vertices, each vertex being represented as an index into the `vertex` array, which is a separate PLY element. The vertices of the point cloud would normally just go into that `vertex` element.
> 2. It looks like your input is a 3D array, which would make sense if you have three coordinates per (row, column) pair in your image. Before encoding as a PLY file, though, you would need to flatten the two (row, column) dimensions into one, with something like
>    ```python
>    (rows, columns) = _3dImage.shape[:2]
>    flattened_image = _3dImage.reshape(rows*columns, -1)
>    ...
>    ```
>    
>    
>    You should then be able to call `PlyElement.describe` on the flattened array. Unfortunately, the width and height of the image won't be directly captured in the PLY file unless you put it in a header comment or something like that.

Aaaaah OK! Let me have a try with this.
