### ISSUE TITLE
binary_little_endian to ascii

### ISSUE THREAD

**Issue by ziwenjie** [dranjan/python-plyfile#47]
Hi, authors:
the plyfile can read the mesh ply files, and how to convert the binary_little_endian to ascii?

Thanks!
Yours, sincerely.

**Comment by dranjan** [comment]
The simplest way is to set the `text` attribute of the `PlyData` instance to `True`.

**Comment by smoluck** [comment]
f_in = open(C://file_in.ply, 'r')
f_out = open(C://file_out.ply, 'w+')

data = plyfile.PlyData.read(f_in)
data.text = True
data.write(f_out)
f_in.close()
f_out.close()

**Comment by dranjan** [comment]
Exactly, @smoluck.

I'm going to close this, since the issue seems to have been resolved.
