### ISSUE TITLE
Accept compressed ply files

### ISSUE THREAD

**Issue by ldv1** [dranjan/python-plyfile#48]
Hi,
Would it be possible to have a `read` method that would accept compressed ply files ? e.g.
`PlyData.read("myfile.ply.bz2")`
?
as in [read_csv](https://pandas.pydata.org/docs/reference/api/pandas.read_csv.html) from pandas.

> compression str or dict, default ‘infer’
> 
>     For on-the-fly decompression of on-disk data.
>     If ‘infer’, then detect compression
>     from the following extensions: ‘.gz’, ‘.bz2’, ‘.zip’, ‘.xz’, or ‘.zst’ (otherwise no compression). 
 >     Set to None for no decompression. 

It must not be as complete or involved as in pandas `read_csv` though.
Thanks!

**Comment by dranjan** [comment]
Hey, sorry for the late reply. I did a quick test and the following seems to work as intended:
```python
import bz2

from plyfile import PlyData

with bz2.open('somefile.ply.bz2') as f:
    ply_data = PlyData.read(f)
```
`plyfile` generally supports reading from file-like objects, so I'm not sure if we should add specific compression formats directly into the API.

**Comment by ldv1** [comment]
Hi,
I recently devised a somewhat similar solution but your solution is cleaner;
I believe, as with `pandas.read_csv()`, it has its place in the API, but it is up to you; at least, people with a similar request can look at this git issue.
Thanks for your help!
