### ISSUE TITLE
Comment serialization throws errors and/or silently loses data

### ISSUE THREAD

**Issue by Zac-HD** [dranjan/python-plyfile#9]
https://gist.github.com/Zac-HD/ea5d9586751e158d0578811a83fdc2b0

In short, the requirements for the comments section is a lot stricter than 'list of unicode strings'.

Requires [Hypothesis](https://hypothesis.readthedocs.io), which I use to generate arbitrary PlyData instances and simplify failing test-cases.

**Comment by dranjan** [comment]
Thanks for the bug report!  Clearly the comments (and obj_info) could use more validation.

**Comment by dranjan** [comment]
I believe this is now addressed on master:
- Leading white space in comments is preserved.
- Embedded newlines are rejected.

Trailing whitespace in comments is not preserved, and I added a note in the README about this.
